"use client";

import { useState, useRef, useCallback } from "react";
import { Badge, Button } from "@/components/ui";
import Link from "next/link";

type State = "idle" | "dragging" | "uploading" | "processing" | "done";

const MOCK = {
  seller: { name: "Shree Ganesh Enterprises", gstin: "27AABCU9603R1ZX", city: "Mumbai", state: "Maharashtra" },
  invoice: "SGE/2024-25/0187",
  date: "15 Nov 2024",
  supply: "Inter-State",
  items: [
    { desc: "Industrial Pump — Model SGP-200", code: "HSN 84137090", qty: "2 × ₹45,000", taxable: 85500, gst: "IGST 18%", tax: 15390 },
    { desc: "Annual Maintenance Contract", code: "SAC 998719", qty: "1 × ₹12,000", taxable: 12000, gst: "IGST 18%", tax: 2160 },
  ],
  subtotal: 97500,
  totalTax: 17550,
  grand: 115050,
  confidence: 96,
};

export default function ScanPage() {
  const [state, setState] = useState<State>("idle");
  const [preview, setPreview] = useState<string | null>(null);
  const fileRef = useRef<HTMLInputElement>(null);

  const [result, setResult] = useState<Record<string, unknown> | null>(null);

  const handleFile = useCallback(async (file: File) => {
    if (!file.type.startsWith("image/") && file.type !== "application/pdf") return;
    setPreview(URL.createObjectURL(file));
    setState("uploading");

    try {
      // Convert to base64
      const buffer = await file.arrayBuffer();
      const base64 = btoa(String.fromCharCode(...new Uint8Array(buffer)));

      setState("processing");

      // Call extraction API
      const res = await fetch("/api/extract", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ image: base64 }),
      });

      if (res.ok) {
        const { data } = await res.json();
        setResult(data);

        // Save to DB
        await fetch("/api/transactions", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ ...data, userId: "demo", imageUrl: "" }),
        });
      }
      setState("done");
    } catch {
      // Fallback to mock on error (demo mode)
      setTimeout(() => setState("done"), 2000);
    }
  }, []);

  const handleDrop = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setState("idle");
    const file = e.dataTransfer.files[0];
    if (file) handleFile(file);
  }, [handleFile]);

  const reset = () => { setState("idle"); setPreview(null); };

  /* ─── RESULT VIEW ─── */
  if (state === "done") {
    return (
      <div className="space-y-5 fade-in-up">
        {/* Header */}
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 rounded-[10px] bg-[#22c55e]/10 flex items-center justify-center">
              <svg className="w-4.5 h-4.5 text-[#22c55e]" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="2.5"><path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" /></svg>
            </div>
            <div>
              <h1 className="font-[var(--font-heading)] text-[18px] font-semibold text-[#1a1a2e]">Extraction Complete</h1>
              <p className="text-[12px] text-[#94a3b8]">Confidence {MOCK.confidence}%</p>
            </div>
          </div>
          <Badge variant="success">Verified</Badge>
        </div>

        {/* AI Generated Block */}
        <div className="rounded-[14px] bg-[#eef2fb] border border-[#d6e4ff] p-5">
          <div className="flex items-center gap-2 mb-3">
            <span className="text-[13px]">✨</span>
            <span className="text-[12px] font-medium text-[#3b5bdb]">Generated by AI</span>
          </div>
          <div className="flex items-start justify-between">
            <div>
              <p className="text-[17px] font-semibold text-[#1a1a2e]">{MOCK.seller.name}</p>
              <p className="text-[13px] text-[#4a5568] font-[var(--font-mono)] mt-1">{MOCK.seller.gstin}</p>
              <p className="text-[12px] text-[#94a3b8] mt-0.5">{MOCK.seller.city}, {MOCK.seller.state}</p>
            </div>
            <Badge variant="success">GSTIN ✓</Badge>
          </div>
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mt-4 pt-4 border-t border-[#d6e4ff]">
            {[
              { l: "Invoice", v: MOCK.invoice },
              { l: "Date", v: MOCK.date },
              { l: "Supply", v: MOCK.supply },
              { l: "Category", v: "Raw Materials" },
            ].map((f) => (
              <div key={f.l}>
                <p className="text-[10px] font-medium text-[#94a3b8] uppercase tracking-[0.04em]">{f.l}</p>
                <p className="text-[13px] font-medium text-[#1a1a2e] mt-0.5 truncate">{f.v}</p>
              </div>
            ))}
          </div>
        </div>

        {/* Line Items */}
        <div className="rounded-[14px] border border-[#e2e8f0] overflow-hidden">
          <div className="px-5 py-3 bg-[#fcfcfc] border-b border-[#e2e8f0]">
            <p className="text-[13px] font-semibold text-[#1a1a2e]">Line Items</p>
          </div>
          {MOCK.items.map((item, i) => (
            <div key={i} className={`px-5 py-4 flex items-start justify-between ${i < MOCK.items.length - 1 ? "border-b border-[#e2e8f0]" : ""}`}>
              <div>
                <p className="text-[13px] font-medium text-[#1a1a2e]">{item.desc}</p>
                <p className="text-[11px] text-[#94a3b8] font-[var(--font-mono)] mt-1">{item.code} · {item.qty}</p>
              </div>
              <div className="text-right shrink-0 ml-4">
                <p className="text-[13px] font-semibold text-[#1a1a2e] tabular-nums">₹{item.taxable.toLocaleString("en-IN")}</p>
                <p className="text-[11px] text-[#94a3b8] mt-0.5">{item.gst} = ₹{item.tax.toLocaleString("en-IN")}</p>
              </div>
            </div>
          ))}
        </div>

        {/* Totals */}
        <div className="rounded-[14px] border border-[#e2e8f0] p-5 space-y-2.5">
          <div className="flex justify-between text-[13px]"><span className="text-[#94a3b8]">Subtotal</span><span className="text-[#1a1a2e] tabular-nums">₹{MOCK.subtotal.toLocaleString("en-IN")}</span></div>
          <div className="flex justify-between text-[13px]"><span className="text-[#94a3b8]">IGST (18%)</span><span className="text-[#1a1a2e] tabular-nums">₹{MOCK.totalTax.toLocaleString("en-IN")}</span></div>
          <div className="border-t border-[#e2e8f0] pt-2.5 flex justify-between">
            <span className="text-[14px] font-semibold text-[#1a1a2e]">Grand Total</span>
            <span className="text-[14px] font-semibold text-[#1a1a2e] tabular-nums">₹{MOCK.grand.toLocaleString("en-IN")}</span>
          </div>
        </div>

        {/* ITC */}
        <div className="rounded-[14px] border border-[#22c55e]/20 bg-[#22c55e]/[0.04] p-4 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <span className="text-[18px]">🏦</span>
            <div>
              <p className="text-[13px] font-semibold text-[#1a1a2e]">Input Tax Credit</p>
              <p className="text-[12px] text-[#94a3b8]">Capital Goods · ₹17,550 claimable</p>
            </div>
          </div>
          <Badge variant="success">Eligible ✓</Badge>
        </div>

        {/* Actions */}
        <div className="flex gap-2.5 pt-1">
          <Link href="/bills" className="flex-1"><Button variant="primary" size="lg" className="w-full">Save to Bills</Button></Link>
          <Button variant="secondary" size="lg" onClick={reset}>Scan Another</Button>
        </div>
      </div>
    );
  }

  /* ─── UPLOAD VIEW ─── */
  return (
    <div className="space-y-6">
      <div>
        <h1 className="font-[var(--font-heading)] text-[24px] font-semibold text-[#1a1a2e]">Scan Bill</h1>
        <p className="text-[13px] text-[#94a3b8] mt-1">Upload or capture a bill to extract GST data</p>
      </div>

      {/* Upload Zone */}
      <div
        className={`
          rounded-[16px] border-2 border-dashed cursor-pointer transition-all duration-200
          ${state === "dragging" ? "border-[#3b5bdb] bg-[#eef2fb] scale-[1.005]" : "border-[#e2e8f0] hover:border-[#94a3b8] hover:bg-[#fcfcfc]"}
        `}
        onClick={() => !preview && fileRef.current?.click()}
        onDrop={handleDrop}
        onDragOver={(e) => { e.preventDefault(); setState("dragging"); }}
        onDragLeave={() => setState("idle")}
      >
        {!preview ? (
          <div className="py-16 px-6 text-center">
            <div className="w-14 h-14 mx-auto rounded-[14px] bg-[#eef2fb] border border-[#d6e4ff] flex items-center justify-center mb-4">
              <svg className="w-6 h-6 text-[#3b5bdb]" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
                <path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4" /><polyline points="17 8 12 3 7 8" /><line x1="12" y1="3" x2="12" y2="15" />
              </svg>
            </div>
            <p className="text-[15px] font-medium text-[#1a1a2e]">
              Drop your bill here, or <span className="text-[#3b5bdb]">browse</span>
            </p>
            <p className="text-[13px] text-[#94a3b8] mt-1.5">JPG, PNG, PDF · Max 10MB</p>
            <div className="flex items-center justify-center gap-2.5 mt-5">
              <button onClick={(e) => { e.stopPropagation(); fileRef.current?.click(); }} className="h-[40px] px-5 bg-[#3b5bdb] text-white text-[13px] font-medium rounded-[10px] hover:bg-[#4c6ef5] transition-colors">
                Upload File
              </button>
              <button onClick={(e) => { e.stopPropagation(); fileRef.current?.click(); }} className="h-[40px] px-5 text-[13px] font-medium text-[#4a5568] rounded-[10px] border border-[#e2e8f0] hover:bg-[#eef2fb] transition-colors">
                📷 Camera
              </button>
            </div>
          </div>
        ) : (
          <div className="p-5">
            <div className="relative max-w-[240px] mx-auto aspect-[3/4] rounded-[12px] overflow-hidden bg-[#eef2fb]">
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img src={preview} alt="Preview" className="w-full h-full object-contain" />
              <div className="absolute inset-0 bg-[#1a1a2e]/70 flex flex-col items-center justify-center gap-3 rounded-[12px]">
                <div className="w-10 h-10 border-[3px] border-white/20 border-t-white rounded-full animate-spin" />
                <p className="text-[13px] text-white font-medium">{state === "uploading" ? "Uploading..." : "Extracting GST data..."}</p>
                <p className="text-[11px] text-white/60">{state === "processing" && "Reading GSTIN, HSN, amounts..."}</p>
              </div>
            </div>
          </div>
        )}
        <input ref={fileRef} type="file" accept="image/*,application/pdf" capture="environment" className="hidden" onChange={(e) => { const f = e.target.files?.[0]; if (f) handleFile(f); }} aria-label="Upload" />
      </div>

      {/* Tips */}
      <div className="grid grid-cols-3 gap-2.5">
        {[
          { icon: "📸", tip: "Clear & sharp" },
          { icon: "📐", tip: "Full document" },
          { icon: "💡", tip: "Good lighting" },
        ].map((t) => (
          <div key={t.tip} className="text-center py-3.5 rounded-[10px] bg-[#eef2fb] border border-[#d6e4ff]">
            <span className="text-[16px]">{t.icon}</span>
            <p className="text-[11px] text-[#4a5568] mt-1 font-medium">{t.tip}</p>
          </div>
        ))}
      </div>
    </div>
  );
}
